name: CI/CD Pipeline with SAST 
on:
   push:
      branches: [ main, master ]
   pull_request: 
      branches: [ main, master ]
jobs: 
  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    steps:
       - name: Checkout code
         uses: actions/checkout@v4
		
       - name: Set up Python
         uses: actions/setup-python@v5 
         with: 
            python-version: '3.10'
      - name: Install dependencies
           run: |
		      python -m pip install --upgrade pip
			  pip install -r requirements.txt
			  pip install pytest 
          - name: Run Bandit SAST Scan 
            run: | 
		       pip install bandit 
		       bandit -r . --severity-level high --confidence-level high -f json -o 
		       bandit_results.json || true 
               id: bandit-check 
               run: | 
		if [ -f bandit_results.json ]; then 
		if jq -e '.results[] | select(.issue_confidence == "HIGH" and .issue_severity 
		== "HIGH")' bandit_results.json; then 
		echo "Bandit found critical vulnerabilities! Failing the pipeline." 
		exit 1 
		else 
		echo "No critical vulnerabilities found by Bandit." 
		fi 
		else 
		echo "Bandit report not found. Assuming no issues." 
		fi 
uses: aquasecurity/trivy-action@master 
with: 
scan-type: 'fs' 
scan-ref: '.' 
format: 'table' 
exit-code: '1' 
ignore-unfixed: true 
severity: 'HIGH,CRITICAL' 
run: | 
		python -m pytest tests/ -v 
